   - name: disabling the module
     ansible.builtin.command: dnf module disable redis -y

   - name: enabling the module
     ansible.builtin.command: dnf module enable redis:7 -y


   - name: install the redis
     ansible.builtin.dnf:
       name: redis
       state: present

   - name: allow remote connections
     ansible.builtin.replace:
       path: /etc/redis/redis.conf
       regexp: "127.0.0.1" 
       replace: "0.0.0.0"

   - name: disable protected-mode connections
     ansible.builtin.lineinfile:
       path: /etc/redis/redis.conf
       regexp: "protected-mode" 
       line: protected-mode no

   - name: enable and start the service
     ansible.builtin.service:
      name: redis 
      state: started
      enabled: yes
